name: Daily Readwise to Feishu Sync

# 每天凌晨3点运行 (北京时间，UTC+8 = 19:00 UTC)
on:
  schedule:
    - cron: '0 19 * * *'  # 每天 UTC 19:00 = 北京时间 03:00
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run sync script
      env:
        READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
        TARGET_TAG: ai101
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_APP_TOKEN: ${{ secrets.FEISHU_APP_TOKEN }}
        FEISHU_TABLE_ID: ${{ secrets.FEISHU_TABLE_ID }}
      run: |
        echo "开始同步任务..."
        echo "环境变量检查："
        echo "- READWISE_TOKEN: ${READWISE_TOKEN:0:10}..."
        echo "- TARGET_TAG: $TARGET_TAG"
        echo "- FEISHU_APP_ID: ${FEISHU_APP_ID:0:10}..."
        echo "- FEISHU_APP_SECRET: ${FEISHU_APP_SECRET:0:10}..."
        echo "- FEISHU_APP_TOKEN: ${FEISHU_APP_TOKEN:0:15}..."
        echo "- FEISHU_TABLE_ID: $FEISHU_TABLE_ID"
        python aireading_bot.py
        echo "同步任务完成"
        
    - name: Upload logs (if needed)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs
        path: "*.log"
        retention-days: 7
        if-no-files-found: ignore